# Generated by Django 4.0.3 on 2022-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('contenido', models.CharField(max_length=200000)),
                ('resumen', models.CharField(max_length=20000)),
                ('imagen', models.CharField(max_length=3000)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
    ]
